//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace NextMove.Lib
{
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [XmlRoot(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", IsNullable=false)]
    public partial class CorrelationInformation {
    
        private System.DateTime requestingDocumentCreationDateTimeField;
    
        private bool requestingDocumentCreationDateTimeFieldSpecified;
    
        private string requestingDocumentInstanceIdentifierField;
    
        private System.DateTime expectedResponseDateTimeField;
    
        private bool expectedResponseDateTimeFieldSpecified;

        /// <remarks/>
        [JsonProperty("requestingDocumentCreationDateTime", NullValueHandling = NullValueHandling.Ignore)]
        public System.DateTime RequestingDocumentCreationDateTime {
            get {
                return this.requestingDocumentCreationDateTimeField;
            }
            set {
                this.requestingDocumentCreationDateTimeField = value;
            }
        }
    
        /// <remarks/>
        //[XmlIgnore()]
        //[JsonIgnore]
        [JsonProperty("requestingDocumentCreationDateTimeSpecified", NullValueHandling = NullValueHandling.Ignore)]
        public bool RequestingDocumentCreationDateTimeSpecified {
            get {
                return this.requestingDocumentCreationDateTimeFieldSpecified;
            }
            set {
                this.requestingDocumentCreationDateTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [JsonProperty("requestingDocumentInstanceIdentifier", NullValueHandling = NullValueHandling.Ignore)]
        public string RequestingDocumentInstanceIdentifier {
            get {
                return this.requestingDocumentInstanceIdentifierField;
            }
            set {
                this.requestingDocumentInstanceIdentifierField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("expectedResponseDateTime")]
        public System.DateTime ExpectedResponseDateTime {
            get {
                return this.expectedResponseDateTimeField;
            }
            set {
                this.expectedResponseDateTimeField = value;
            }
        }
    
        /// <remarks/>
        //[XmlIgnore()]
        //[JsonIgnore]
        public bool ExpectedResponseDateTimeSpecified {
            get {
                return this.expectedResponseDateTimeFieldSpecified;
            }
            set {
                this.expectedResponseDateTimeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class Scope {
    
        private string typeField;
    
        private string instanceIdentifierField;
    
        private string identifierField;
    
        private object[] scopeInformationField;

        /// <remarks/>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("instanceIdentifier", NullValueHandling = NullValueHandling.Ignore)]
        public string InstanceIdentifier {
            get {
                return this.instanceIdentifierField;
            }
            set {
                this.instanceIdentifierField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("identifier", NullValueHandling = NullValueHandling.Ignore)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("ScopeInformation")]
        [JsonProperty("scopeInformation", NullValueHandling = NullValueHandling.Ignore)]
        public CorrelationInformation[] ScopeInformation {
            get
            {
                return (CorrelationInformation[]) this.scopeInformationField;
            }
            set {
                this.scopeInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class ManifestItem {
    
        private string mimeTypeQualifierCodeField;
    
        private string uniformResourceIdentifierField;
    
        private string descriptionField;
    
        private string languageCodeField;

        /// <remarks/>
        [JsonProperty("mimeTypeQualifierCode")]
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="anyURI")]
        [JsonProperty("uniformResourceIdentifier", NullValueHandling = NullValueHandling.Ignore)]
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("languageCode", NullValueHandling = NullValueHandling.Ignore)]
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class Manifest {
    
        private string numberOfItemsField;
    
        private ManifestItem[] manifestItemField;
    
        /// <remarks/>
        [XmlElement(DataType="integer")]
        [JsonProperty("numberOfItems", NullValueHandling = NullValueHandling.Ignore)]
        public string NumberOfItems {
            get {
                return this.numberOfItemsField;
            }
            set {
                this.numberOfItemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("ManifestItem")]
        [JsonProperty("manifestItem", NullValueHandling = NullValueHandling.Ignore)]
        public ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class DocumentIdentification {
    
        private string standardField;
    
        private string typeVersionField;
    
        private string instanceIdentifierField;
    
        private string typeField;
    
        private bool multipleTypeField;
    
        private bool multipleTypeFieldSpecified;
    
        private System.DateTime creationDateAndTimeField;

        /// <remarks/>
        [JsonProperty("standard", NullValueHandling = NullValueHandling.Ignore)]
        public string Standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("typeVersion", NullValueHandling = NullValueHandling.Ignore)]
        public string TypeVersion {
            get {
                return this.typeVersionField;
            }
            set {
                this.typeVersionField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("instanceIdentifier", NullValueHandling = NullValueHandling.Ignore)]
        public string InstanceIdentifier {
            get {
                return this.instanceIdentifierField;
            }
            set {
                this.instanceIdentifierField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("multipleType", NullValueHandling = NullValueHandling.Ignore)]
        public bool MultipleType {
            get {
                return this.multipleTypeField;
            }
            set {
                this.multipleTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        [JsonIgnore]
        public bool MultipleTypeSpecified {
            get {
                return this.multipleTypeFieldSpecified;
            }
            set {
                this.multipleTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [JsonProperty("creationDateAndTime", NullValueHandling = NullValueHandling.Ignore)]
        public System.DateTime CreationDateAndTime {
            get {
                return this.creationDateAndTimeField;
            }
            set {
                this.creationDateAndTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class ContactInformation {
    
        private string contactField;
    
        private string emailAddressField;
    
        private string faxNumberField;
    
        private string telephoneNumberField;
    
        private string contactTypeIdentifierField;

        /// <remarks/>
        [JsonProperty("contact", NullValueHandling = NullValueHandling.Ignore)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("emailAddress", NullValueHandling = NullValueHandling.Ignore)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("faxNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("telephoneNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string TelephoneNumber {
            get {
                return this.telephoneNumberField;
            }
            set {
                this.telephoneNumberField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("contactTypeIdentifier", NullValueHandling = NullValueHandling.Ignore)]
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class PartnerIdentification {
    
        private string authorityField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("authority", NullValueHandling = NullValueHandling.Ignore)]
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class Partner {
    
        private PartnerIdentification identifierField;
    
        private ContactInformation[] contactInformationField;

        /// <remarks/>
        [JsonProperty("identifier", NullValueHandling = NullValueHandling.Ignore)]
        public PartnerIdentification Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("ContactInformation")]
        [JsonProperty("contactInformation", NullValueHandling = NullValueHandling.Ignore)]
        public ContactInformation[] ContactInformation {
            get {
                return this.contactInformationField;
            }
            set {
                this.contactInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class ServiceTransaction {
    
        private TypeOfServiceTransaction typeOfServiceTransactionField;
    
        private bool typeOfServiceTransactionFieldSpecified;
    
        private string isNonRepudiationRequiredField;
    
        private string isAuthenticationRequiredField;
    
        private string isNonRepudiationOfReceiptRequiredField;
    
        private string isIntelligibleCheckRequiredField;
    
        private string isApplicationErrorResponseRequestedField;
    
        private string timeToAcknowledgeReceiptField;
    
        private string timeToAcknowledgeAcceptanceField;
    
        private string timeToPerformField;
    
        private string recurrenceField;
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("typeOfServiceTransaction", NullValueHandling = NullValueHandling.Ignore)]
        public TypeOfServiceTransaction TypeOfServiceTransaction {
            get {
                return this.typeOfServiceTransactionField;
            }
            set {
                this.typeOfServiceTransactionField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        [JsonIgnore]
        public bool TypeOfServiceTransactionSpecified {
            get {
                return this.typeOfServiceTransactionFieldSpecified;
            }
            set {
                this.typeOfServiceTransactionFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("isNonRepudiationRequired", NullValueHandling = NullValueHandling.Ignore)]
        public string IsNonRepudiationRequired {
            get {
                return this.isNonRepudiationRequiredField;
            }
            set {
                this.isNonRepudiationRequiredField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("isAuthenticationRequired", NullValueHandling = NullValueHandling.Ignore)]
        public string IsAuthenticationRequired {
            get {
                return this.isAuthenticationRequiredField;
            }
            set {
                this.isAuthenticationRequiredField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("isNonRepudiationOfReceiptRequired", NullValueHandling = NullValueHandling.Ignore)]
        public string IsNonRepudiationOfReceiptRequired {
            get {
                return this.isNonRepudiationOfReceiptRequiredField;
            }
            set {
                this.isNonRepudiationOfReceiptRequiredField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("isIntelligibleCheckRequired", NullValueHandling = NullValueHandling.Ignore)]
        public string IsIntelligibleCheckRequired {
            get {
                return this.isIntelligibleCheckRequiredField;
            }
            set {
                this.isIntelligibleCheckRequiredField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("isApplicationErrorResponseRequested", NullValueHandling = NullValueHandling.Ignore)]
        public string IsApplicationErrorResponseRequested {
            get {
                return this.isApplicationErrorResponseRequestedField;
            }
            set {
                this.isApplicationErrorResponseRequestedField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("timeToAcknowledgeReceipt", NullValueHandling = NullValueHandling.Ignore)]
        public string TimeToAcknowledgeReceipt {
            get {
                return this.timeToAcknowledgeReceiptField;
            }
            set {
                this.timeToAcknowledgeReceiptField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("timeToAcknowledgeAcceptance", NullValueHandling = NullValueHandling.Ignore)]
        public string TimeToAcknowledgeAcceptance {
            get {
                return this.timeToAcknowledgeAcceptanceField;
            }
            set {
                this.timeToAcknowledgeAcceptanceField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("timeToPerform", NullValueHandling = NullValueHandling.Ignore)]
        public string TimeToPerform {
            get {
                return this.timeToPerformField;
            }
            set {
                this.timeToPerformField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [JsonProperty("recurrence", NullValueHandling = NullValueHandling.Ignore)]
        public string Recurrence {
            get {
                return this.recurrenceField;
            }
            set {
                this.recurrenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public enum TypeOfServiceTransaction {
    
        /// <remarks/>
        RequestingServiceTransaction,
    
        /// <remarks/>
        RespondingServiceTransaction,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [XmlRoot(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", IsNullable=false)]
    public partial class BusinessService {
    
        private string businessServiceNameField;
    
        private ServiceTransaction serviceTransactionField;

        /// <remarks/>
        [JsonProperty("businessServiceName", NullValueHandling = NullValueHandling.Ignore)]
        public string BusinessServiceName {
            get {
                return this.businessServiceNameField;
            }
            set {
                this.businessServiceNameField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("serviceTransaction", NullValueHandling = NullValueHandling.Ignore)]
        public ServiceTransaction ServiceTransaction {
            get {
                return this.serviceTransactionField;
            }
            set {
                this.serviceTransactionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [XmlRoot(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", IsNullable=false)]
    public partial class StandardBusinessDocumentHeader {
    
        private string headerVersionField;
    
        private Partner[] senderField;
    
        private Partner[] receiverField;
    
        private DocumentIdentification documentIdentificationField;
    
        private Manifest manifestField;
    
        private Scope[] businessScopeField;

        /// <remarks/>
        [JsonProperty("headerVersion", NullValueHandling = NullValueHandling.Ignore)]
        public string HeaderVersion {
            get {
                return this.headerVersionField;
            }
            set {
                this.headerVersionField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Sender")]
        [JsonProperty("sender", NullValueHandling = NullValueHandling.Ignore)]
        public Partner[] Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Receiver")]
        [JsonProperty("receiver", NullValueHandling = NullValueHandling.Ignore)]
        public Partner[] Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
    
        /// <remarks/>
        [JsonProperty("documentIdentification", NullValueHandling = NullValueHandling.Ignore)]
        public DocumentIdentification DocumentIdentification {
            get {
                return this.documentIdentificationField;
            }
            set {
                this.documentIdentificationField = value;
            }
        }

        /// <remarks/>
        [JsonProperty("manifest", NullValueHandling = NullValueHandling.Ignore)]
        public Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
    
        /// <remarks/>
        [XmlArrayItem(IsNullable=false)]
        
        [JsonProperty("businessScope", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(SingleOrArrayConverter<string>))]
        public Scope[] BusinessScope {
            get {
                return this.businessScopeField;
            }
            set {
                this.businessScopeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [XmlRoot(Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", IsNullable=false)]
    public partial class StandardBusinessDocument {
    
        private StandardBusinessDocumentHeader standardBusinessDocumentHeaderField;
    
        private System.Xml.XmlElement anyField;

        /// <remarks/>
        [JsonProperty("standardBusinessDocumentHeader", NullValueHandling = NullValueHandling.Ignore)]
        public StandardBusinessDocumentHeader StandardBusinessDocumentHeader {
            get {
                return this.standardBusinessDocumentHeaderField;
            }
            set {
                this.standardBusinessDocumentHeaderField = value;
            }
        }
    
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
}